### ISSUE TITLE
automatic paste ^V

### ISSUE THREAD

**Issue by dcrystalj** [shantzu/ClipIt#45]
I enabled this option ```automatic paste```. if i run in terminal to paste something all i see is ^V. This feature was working for me in diodon but im looking for alternatives since diodon has crashed.

**Comment by shantzu** [comment]
The autopaste feature just executes a 'Ctrl+V' key combination whenever it tries to paste something. Many terminals allow you to specify custom key combinations for paste. You would need to Change the key combination in your terminal to 'Ctrl+V' for this to work.
